name: Bug Report
description: Report bugs to help us identify, replicate, and resolve issues effectively. Provide as much detail as possible.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Provide a clear and concise description of the bug.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue in detail, including what you expected to happen and what actually occurred.
      placeholder: Provide a detailed description of the bug.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Steps to Reproduce
        Provide step-by-step instructions to reproduce the bug.

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: Describe the steps clearly.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Expected Behavior
        Describe what you expected to happen.

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe the expected outcome.
      placeholder: Explain what should happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Actual Behavior
        Describe what actually happened instead.

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe the actual outcome.
      placeholder: Explain what actually happened.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Screenshots or Logs
        If applicable, add screenshots or logs to help explain your problem.

  - type: textarea
    id: screenshots_or_logs
    attributes:
      label: Screenshots/Logs
      description: Provide any relevant screenshots or logs.
      placeholder: Add screenshots or paste logs here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Additional Context
        Add any other context about the problem here.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Include any other information that might be relevant.
      placeholder: Add any additional context here.
    validations:
      required: false
